sudo: required
language: python
python:
- '2.7'
services:
- docker
before_install:
# get the docker image to run phoenix
- docker pull redis
# run the image with port forwarding
- docker run -itd -p 6379:6379 redis
# make sure our container started successfully
- docker ps -a

install:
- pip install -r dev-requirements.txt
- pip install -r requirements.txt

script:
- flake8 celldb tests
- docker ps -a
- nosetests

deploy:
  provider: pypi
  user: david4096
  password:
    secure: knR3ctncIkOSaRsTgn4Jv8Dohz7i2C3G6m0+bFwYcoeVaZP06JIb6cldfFgo0Y2jXQyym2K4jaQLT/3GM6xC7qM4/ccYC6TqCSqe4ECf3ySfwvJAqJf1BOAlpvtzD+p6AHz1dJZmGXbTWbq+sGudmv8nDa6vXRND1BhZ/amPf6FNmdNW2dacpnuJLnreQ/r9T/Um6xfWv3L2TDwPadxpiTyECoPmEY0s0F3SHiCTUPWM6pnq6JKZnKUGAZiugUGb9OBcxaPAtYNGRHZFYbTw2dzCcmO7vPMhS6UcgE4aRbY8dXEW5s9ct4uwVgPUbMszBP3p195GZ/Z+IguHAFkkIrpjuWjeVvD9CKvdNibp4bLctlpOnH40OB1qXAmjvQM/oo0bLgVMEB+sxeK6nVNCmh2dioGT2fkwtJXEofYUGfHU6rm9wKSLP7S2LfIXEbCiMU4DfpPVuKoafhRTLX4x4KXkxJrfCSyBed+xJPi1uYWC9RkrdaoTO1YxRYyI+YHTTamjIZfNHWjN0mIqofgC4P75jksC/Smd8Q3hoA/NX6DHoTdtBeCpvcUkL+x3MGO9li9iHVlHWiAzu1udcO/bluwoFTwte2FuNNOi3T66GJdPx6yHTMpTu0CzzwjKobjrwnazOX4aiigcl3D+5EsG8KYq7/Chn6ZnjWHLKJMgoOc=
  skip_upload_docs: true
  distributions: "sdist bdist_wheel"
  on:
    repo: david4096/celldb
tags: true
