sudo: required

language: python
python:
  - "2.7"

services:
  - docker

before_install:
  - docker pull david4096/docker-phoenix
  - docker run -itd -p 8765:8765 david4096/docker-phoenix
  - sleep 45
  - docker ps -a

install:
  - pip install -r dev-requirements.txt
  - pip install -r requirements.txt

script:
  - flake8 celldb tests
  - docker ps -a
  - nosetests
